---
name: Build OCI Images
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  collect-image-dirs:
    runs-on: ubuntu-latest
    outputs:
      image_dirs: ${{ steps.collect-dirs.outputs.dirs }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Collect image directories
        id: collect-dirs
        run: |
          dirs=$(python ./oci-images/image-specs/collect_image_directories.py)
          echo "dirs=$dirs" >> $GITHUB_OUTPUT
  build-images:
    needs: collect-image-dirs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_dir: ${{ fromJson(needs.collect-image-dirs.outputs.image_dirs) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image_dir }}
          push: false
          platforms: linux/arm64
          tags: ${{ github.repository }}:${{ github.sha }}-${{ matrix.image_dir }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
